import {careerRows} from './career-data.js?v=23';
import {escapeHtml as esc,formatNumber as num} from './public-data.js';
export function renderCareer(host,data,name,partial=false){
 const rows=careerRows(data,name),valid=rows.filter(r=>r.player?.games>0);
 if(!valid.length){host.innerHTML='<p>Noch keine Saisonwerte vorhanden.</p>';return}
 const values=valid.map(r=>Number(r.player.average));const lo=Math.max(0,Math.floor((Math.min(...values)-10)/10)*10),hi=Math.ceil((Math.max(...values)+10)/10)*10;
 const x=i=>45+i*610/Math.max(1,rows.length-1),y=v=>160-(v-lo)/(hi-lo)*120;
 let segments=[],segment=[];
 rows.forEach((r,i)=>{if(r.player?.games>0)segment.push(`${x(i)},${y(r.player.average)}`);else if(segment.length){segments.push(segment);segment=[]}});if(segment.length)segments.push(segment);
 const chart=`<svg viewBox="0 0 700 220" role="img" aria-label="Saisonschnitt von ${esc(name)}; genaue Werte in der Tabelle darunter"><line x1="45" y1="160" x2="665" y2="160" stroke="#9eafa6"/>${[lo,(lo+hi)/2,hi].map(v=>`<text x="2" y="${y(v)+4}" font-size="13" fill="#35534d">${v}</text><line x1="45" x2="665" y1="${y(v)}" y2="${y(v)}" stroke="#d0ded6"/>`).join('')}${segments.map(p=>`<polyline points="${p.join(' ')}" fill="none" stroke="#087e80" stroke-width="3"/>`).join('')}${rows.map((r,i)=>`${r.player?.games>0?`<circle cx="${x(i)}" cy="${y(r.player.average)}" r="5" fill="#a96618"><title>${esc(r.seasonName)}: Ø ${num(r.player.average)}</title></circle><text x="${x(i)}" y="${y(r.player.average)-12}" text-anchor="middle" font-size="15" fill="#173d3c">${num(r.player.average)}</text>`:''}<text x="${x(i)}" y="188" text-anchor="middle" font-size="14" fill="#35534d">${esc(r.seasonId.slice(0,4))}<tspan x="${x(i)}" dy="18">${esc(r.seasonId.split('-')[1].toUpperCase())}</tspan></text>`).join('')}</svg>`;
 host.innerHTML=`<div class="career-heading"><div><span class="profile-eyebrow">Deine Entwicklung</span><h2>Von Saison zu Saison</h2></div><span>${valid.length} erfasste Saisons</span></div>${chart}<p class="profile-note">Saisonschnitt je erfasster Saison. Die laufende Saison zeigt den aktuellen Stand. Lücken bedeuten: kein eindeutig zuordenbarer Wert.${partial?' Einige Saisondaten konnten nicht geladen werden.':''}</p><details><summary>Alle Saisonwerte ansehen</summary><table class="career-table"><thead><tr><th>Saison</th><th>Team</th><th>Platz</th><th>Spiele</th><th>Ø</th><th>Bestes Spiel</th></tr></thead><tbody>${valid.map(r=>`<tr><td>${esc(r.seasonName.replace('Liga ',''))}</td><td>${esc(r.player.team)}</td><td>${r.player.rank}</td><td>${r.player.games}</td><td>${num(r.player.average)}</td><td>${r.player.bestGame}</td></tr>`).join('')}</tbody></table></details>`;
}
